server:
  port: 8000
spring:
  application:
    name: admin-server
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:admin@standalone:30001/eureka/